export const COLORS = {
  primary:        '#0A3D8F',
  primaryDark:    '#072D6B',
  primaryLight:   '#1565C0',
  primarySurface: '#E8F0FE',
  background:     '#F0F4FF',
  card:           '#FFFFFF',
  headerBg:       '#0A3D8F',
  normal:         '#2E7D32',
  normalBg:       '#E8F5E9',
  normalBorder:   '#A5D6A7',
  navy:           '#0A2352',   
  ocean:          '#1352A2',   
  wave:           '#2196F3',   
  teal:           '#00BFA5',   
  seafoam:        '#E3F4F4',   
  sky:            '#EAF3FB',   
  warning:        '#F57F17',
  warningBg:      '#FFF8E1',
  warningBorder:  '#FFE082',
  critical:       '#C62828',
  criticalBg:     '#FFEBEE',
  criticalBorder: '#EF9A9A',
  textPrimary:    '#1A1A2E',
  textSecondary:  '#555770',
  textMuted:      '#9E9EB8',
  textOnPrimary:  '#FFFFFF',
  textInfo:       '#90CAF9',
  border:         '#E0E8FF',
  borderDark:     '#C5D0F0',
  online:         '#69F0AE',
  white:          '#FFFFFF',
  black:          '#000000',
};

export const STATUS_COLORS = {
  normal:   { text: COLORS.normal,   bg: COLORS.normalBg,   border: COLORS.normalBorder },
  warning:  { text: COLORS.warning,  bg: COLORS.warningBg,  border: COLORS.warningBorder },
  critical: { text: COLORS.critical, bg: COLORS.criticalBg, border: COLORS.criticalBorder },
};